global using Microsoft.AspNetCore.Http;
global using Microsoft.AspNetCore.Http.HttpResults;
global using Microsoft.AspNetCore.Mvc;
global using System;
global using VideoConferenceApi.DTO;
global using VideoConferenceApi.Entities;
global using VideoConferenceApi.BL.Interfaces;
global using VideoConferenceApi.DAL.Interfaces;
global using VideoConferenceApi.BL.Services;
global using System.ComponentModel.DataAnnotations.Schema;
global using System.ComponentModel.DataAnnotations;
global using Microsoft.EntityFrameworkCore;
global using Action = VideoConferenceApi.Entities.Action;